### PR TITLE
xdg-terminal-exec: Move more code into functions

### PR DESCRIPTION
**Pull request by fluvf**
See commit messages for details

Now that most functionality is in separate functions, tests could be written for each individually
Should make for a simpler and more comprehensive set of test

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
I'm afraid, this slows down execution significantly: On my machine:

- baseline `xterm -e /bin/true`: 0,062s
- `xdg-terminal-exec /bin/true` master with xterm: 0,116s
- `xdg-terminal-exec /bin/true` this PR with xterm: 1,242s

**Comment by fluvf** [comment]
I assume you're using `XTE_STOCK_TERMINALS=true`
And yes, it's the removal of that `grep` filter
#32 tries to fix that
On my slow disk machine, the `grep` subshell adds about a second over this PR
If even #32 is slow for you, I think moving to awk should be considered

**Comment by Vladimir-csp** [comment]
#32 is still on the slow side, 0,904s. What do you have in mind with awk?

**Comment by fluvf** [comment]
Before that whole conversation, is the performance a real problem?
What we're discussing is the fallback case.
Having to read _all_ entry files in a system is never ideal, that's why `xdg-terminals.list` exists.
With 15 existing, but invalid, extra entries to read and check
`env XTE_STOCK_TERMINALS=true xdg-terminal-exec /bin/true`
takes my fast machine 0.10 seconds, and slow one 0.91
Going through all 80 and 68 of them takes 0.24 and 2.67 respectively
With just one valid entry, `time` is not really accurate enough to measure the difference
I think that's plenty fast

Now, if an empty `xdg-terminals.list` is to be considered the common case, then it might make sense to rewrite the whole script in `awk`Shell `read` is just slow. `awk` is designed to process files in this way. It's also [POSIX standardised](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html#tag_20_06)
The existing script could be modified to only do the `*.desktop` reads using `awk`, but at that point the rest would be trivial to convert as well.

**Comment by fluvf** [comment]
To be clear, my slow machine spends most of it's execution time on the `find` call
`env XTE_STOCK_TERMINALS=true xdg-terminal-exec /bin/true` with a single entry takes 0.59, with the actual entry read being a fraction of that
I'm working on the assumption that the entry reads are the bottleneck

**Comment by Vladimir-csp** [comment]
In my case the culprit seems to be  `entry_id=$(printf '%s' "$entry_path" | tr '/' '-')`. `tr` is called for a lot of entries.

**Comment by Vladimir-csp** [comment]
Replaced `tr` with a function. went from 1,193s to 0,717s

**Comment by fluvf** [comment]
That's great!
Have you tested #32 with this? It mostly exists because `match_entry_path` was slow
We could also add a special case for the shell supporting `${var/pattern/string}` expansion
It's not POSIX, but most (if not all relevant) shells implement it
It'd imagine it'd be even faster

Apparently GNU implemented a `POSIXLY_CORRECT` env variable, to enable strict POSIX compliance
Maybe we could do the same? It might be a bit overkill depending on how hard checking for that expansion support is

**Comment by fluvf** [comment]
I'll see if moving the `tr` call further back, to apply to the complete `ENTRY_IDS` list, would help
If a single `tr` call is similarly efficient to that in-shell function, I'd prefer it for having less code to maintain

**Comment by fluvf** [comment]
Please test [this branch](https://github.com/fluvf/xdg-terminal-exec/tree/tr_test), and let me know if it helps!
On my slow machine, this PR without your commit takes ~8 seconds, with it ~4.5
#32 takes 2.6, and so does the test branch
My fast machine sees a small improvement against #32, going from 0.24, to 0.20, but I don't know trust worthy those measurements are

**Comment by Vladimir-csp** [comment]
Yes, it's even faster!
32 + sub patch: 0,547s
32 + single tr patch: 0,278s

**Comment by fluvf** [comment]
Great! I'll clean that up and push it with #32 later today then :+1:

**Comment by Vladimir-csp** [comment]
`entry_ids` and `entry_paths` need to be called with empty default, irregardless of whether we fall back to xterm or not.
```
 ✗ uses xterm -e as the fallback
   (from function `assert_success' in file test/tests.bats, line 20,
    in test file test/tests.bats, line 36)
     `assert_success' failed
   status: 2
   output: /home/psycho/Scripts/xdg-terminal/test/../xdg-terminal-exec: 138: entry_ids: parameter not set
   /home/psycho/Scripts/xdg-terminal/test/../xdg-terminal-exec: 141: entry_paths: parameter not set
```
Let's finalize on 32 + single tr + 33

**Comment by fluvf** [comment]
I've rebased this, #32 and #33

**Comment by fluvf** [comment]
Superseded by #32

**Pull request closed without merging**
