### PR TITLE
xdg-terminal-exec: Introduce `error`

### PR DESCRIPTION
**Pull request by fluvf**
Cleans up all those `echo` calls

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
is there any difference in speed between a function and an alias?

**Comment by fluvf** [comment]
Based on some very quick and dirty tests, aliases seem faster than functions
I had to execute over ten million iterations of both before the difference was significant (5s vs. 6s), so I doubt it will ever become a realistic bottleneck :smile:

**Comment by Vladimir-csp** [comment]
naked aliases seem a bit faster than functions in dash and a lot faster in bash. (damn, bash is so sluggish...)

**Comment by Vladimir-csp** [comment]
Thanks!

**Comment by fluvf** [comment]
Yeah, subshells will do that
I'd avoid them if at all possible, creating them is a bit expensive, although I don't know how much that matters in this case

**Pull request merged**
