### PR TITLE
add makefile

### PR DESCRIPTION
**Pull request by quantenzitrone**
i added a makefile
not sure if you want that or not, if not feel free to close this
this is also the first makefile i wrote, so idk if i did everything correctly

i tried to follow the [gnu makefile conventions](https://www.gnu.org/prep/standards/html_node/Makefile-Conventions.html)

### CODE REVIEW

**Comment by keithbowes** [comment]
It doesn't look too bad. Usually, though, there's only one .PHONY target, followed by a space-separated list of phony targets, instead of a separate .PHONY target before each phony target.

Having separate phony targets seems analogous to:
```
install: install-bin
install: install-man
```
instead of `install: install-bin install-man`

I'm pretty sure that .PHONY is a GNU extension and is of limited utility even in GNU make; it's not part of [the POSIX make sepecification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) anyway.

**Comment by Vladimir-csp** [comment]
Thanks, it starts to become handy as now there are more than two files in the project to install.
I hope it doesn't blow up any further, but I thought that [uwsm](https://github.com/Vladimir-csp/uwsm) could be a single shell script at some point...

**Comment by quantenzitrone** [comment]
> It doesn't look too bad. Usually, though, there's only one .PHONY target, followed by a space-separated list of phony targets, instead of a separate .PHONY target before each phony target.

I've only seen the separate `.PHONY <target-name>` in front of each phony target style, e.g. here:
https://github.com/TheNetAdmin/Makefile-Templates/blob/1dd26c3c19793de7637c8752e49fa620dde34c59/SmallProject/Template/Makefile

> I'm pretty sure that .PHONY is a GNU extension and is of limited utility even in GNU make; it's not part of [the POSIX make sepecification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) anyway.

{Open,Free,Net}BSDs make implementations all support the `.PHONY` special target. Only the make implementations on some proprietary UNIXes like AIX or HP-UX, strictly follow POSIX.

**Comment by Vladimir-csp** [comment]
Something does not work here.
```
$ make install -n
Makefile:30: warning: overriding recipe for target 'install-bin'
Makefile:26: warning: ignoring old recipe for target 'install-bin'
Makefile:9: *** Could not find gzip in PATH, please install it.  Stop.
```
`@command...` does not work for some reason.

What are `.PHONY:` targets?

**Comment by Vladimir-csp** [comment]
Fixed it. Thanks!

**Pull request merged**
